library(SDSFoundations)
acl <-AustinCityLimits

# Primary Research Question
# For artists age 30 or older, do female artists play different kinds of music on Austin City Limits than male artists?

#### Examine the Data ####
# 1a. How many artists are in this dataset?
116 by inspection of acl dataframe
# 1b. How many of the first 10 artists in the dataset were Grammy winners?
top10 = acl[1:10, ]
table(top10$Grammy)
4
# 1c. What genre was played by the first female artist in the dataset who was over 60 years of age?
age = acl[acl$Age > 60 & acl$Gender == "F",]
Jazz/Blues
# 2a. Which variable tells us the kind of music played by each artist? The variable name in the dataset is:
Genre
# 2b. What type of variable is this?
Categorical
# 2c. Which variable tells us whether the lead singer or performer is male or not?
Gender
# 2b. What type of variable is this?
Categorical

# Which method should we be using for this analysis and why?
# 3. We will generate a contingency table of genre and gender to help us with this analysis. Why?
  The table will show us how many male and female artists played each type of music. 
# 4. We will compare marginal and conditional probabilities to determine if female and male artists tend to play different kinds of music. Why?
  We want to determine if two categorical variables are independent or not.

#### Prepare for the Analysis #####

# Breakdown Your Analysis
#   Let's break this analysis into its required steps:
# 1. Create a subset of the data for artists age 30 or older.
# 2. Create a table to show the marginal distribution for each variable.  
# 3. Create a contingency table to show the conditional distribution for gender and genre.  
# 4. Make a bar chart to better visualize how many male and female artists played in each genre.
# 5. Calculate P(A):  the probability of each type of music (genre) being played.
# 6. Calculate P(A|B):  the probability of each genre, given the artist's gender.
# 7. Interpret what these probabilities tell us about the relationship between genre and gender.  

# Here is the code you will use:
#   #Subset the data for artists age 30 or older
  older <-acl[acl$Age>=30,]
 
# Create tables of marginal distributions
  genre <- table(older$Genre)
  genre
  gender <- table(older$Gender)
  gender
 
# Create contingency table 
  twoway <- table(older$Gender,older$Genre)
  twoway
 
# Visualize the counts
  barplot(twoway, legend=T, beside=T)
   
# Calculate P(A): the probability of each genre being played
  prop.table(genre)
 
# Calculate P(A|B): the probability of each genre being played, given the artist's gender
  prop.table(twoway, 1)
  
  ### Problem questions ###
# 1) How many columns will be present in the table generated by the following line of code?
  gender <- table(acl$Gender)
  2
# 2) This code produces a bar chart with both a legend and side-by-side bars for each gender:
  barplot(twoway, legend=TRUE, beside=TRUE)
  barplot(twoway, main = "Gender by Genre", xlab="Genre", ylab ="Counts", beside = T, legend = T)
  
  # What would the code look like if we wanted to keep the legend but stack the bars (instead of set them side-by-side)?
  barplot(twoway, legend=TRUE)
  
# 3) This line of code will produce four values, one for each genre of music:
  prop.table(genre)
# What value should you get if you sum the four values together?
  1.00

# 4) What does the value "1" refer to in this line of code:
  prop.table(twoway,1)
# The number 1 references the first variable (gender) listed in the contingency table code.

# 5) Suppose we ran the following code to find conditional probabilities. What error has caused the prop.table function to not work? (You may want to examine the dataset in R for help.)
  acl <- AustinCityLimits
  View(acl)
  gender_grammy <- table(acl$Gender, acl$Grammy)
  prop.table(acl$Gender, acl$Grammy, 1)

  Error in prop.table(acl$Gender, acl$Grammy, 1) : unused argument (1)
# The prop.table function needs a table as an argument.
  
#### Conduct the Analysis ####
  
# Primary Research Question
# For artists age 30 or older, do female artists play different kinds of music on Austin City Limits than male artists? 

  ### Problem questions ###
  
  # 1a. How many male artists are in the 30+ year old artist subset of the Austin City Limits dataset?
  77
  
  # 1b. How many female artists are in the 30+ year old artist subset of the Austin City Limits dataset?
  25
  
  # 2a. To determine the proportion of jazz performers that were male, you would divide ___7___ by __11___. (Enter responses in the order listed in the quesiton.) 
  
  # 2b. To determine the proportion of males that performed jazz, you would divide ___7___ by ___77___. (Enter responses in the order listed in the quesiton.)

    # 3a. Which table should you look at to determine how many artists performed rock/folk/indie music: genre or gender?
  genre
  
  # 3b. How many artists performed rock/folk/indie music?
  61
  
  # 4a. Which of these lines of code provides the probability that a randomly selected artist from the dataset performed rock/folk/indie music?
  prop.table(genre)
  
  # 4b. What is the probability that a randomly selected artist from the dataset performed rock/folk/indie music?
  0.598
  
  # 5a. Which of these lines of code provides the probability that a randomly selected female artist performed rock/folk/indie music?
  prop.table(twoway, 1)
  
  # 5b. What is the probability that a randomly selected female artist performed rock/folk/indie music?
  0.320
  # 6. For genre and gender to be independent, which of the following statements must be true?
  P(rock) = P(rock|female)
  
#### Draw Conclusions #####
  
# Answer the question and support your answer with statistics:
#   
#   The music played on Austin City Limits was grouped into four genres, including Country, Jazz, Rock and Singer-Songwriter. We wanted to examine only those artists who were age 30 or older. Rock was the most frequently played genre, performed by 59.8% of the Austin City Limits artists. Among female artists, however, only 32.0% of the artists played Rock music. This difference between the marginal and conditional probabilities suggests that gender and genre are not independent. This difference was also evident in the bar plots, where it was evident that females were more likely to perform in the Singer-Songwriter category than their male counterparts.